<?php

/**
 * @file
 * Discount module file.
 *
 * Issues a token upon registration.
 */

/**
 * Implements hook_menu().
 */
function discount_menu() {
  $items = array();

  $items['discount'] = array(
    'title' => 'Discount',
    'description' => 'This is discount.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('discount_form'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'user_is_logged_in',
    'access arguments' => array(1),
    'file' => 'includes/discount.form.inc',
  );

  $items['admin/config/discount'] = array(
    'title' => 'Discount',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('discount_config_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/discount.admin.inc',
  );

  return $items;
}

/**
 * Implements form_FORM_ID_alter().
 */
function discount_form_user_register_form_alter(&$form, &$form_state, $form_id) {

  $form['#submit'][] = 'discount_form_submit';
}

/**
 * Implements hook_token_info().
 */
function discount_token_info() {

  $type = array(
    'name' => t('Discount'),
    'description' => t('Discount data.'),
  );

  $discount['code'] = array(
    'name' => t('Discount code'),
    'description' => t('Discount code.'),
  );

  return array(
    'types' => array('discount' => $type),
    'tokens' => array('discount' => $discount),
  );
}

/**
 * Implements hook_tokens().
 */
function discount_tokens($type, $tokens, array $data = array(), array $options = array()) {

  global $user;
  $replacements = array();

  if ($type == 'discount') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'code':

          $code = db_query("SELECT discount FROM {discount_discount} WHERE uid = '$user->uid'")->fetchField();
          if ($code) {
            $replacements[$original] = $code;
          }
          else {
            $replacements[$original] = 'not found';
          }
          break;
      }
    }
  }

  return $replacements;
}

/**
 * Main function.
 */
function discount_form_submit($form, &$form_state) {

  global $user;
  $discount_value = array(
    'uid' => $user->uid,
    'discount'  => substr(uniqid(), 3),
  );
  drupal_write_record('discount_discount', $discount_value);
  $form_state['redirect'] = 'discount';
}
