<?php

/**
 * @file
 * Discount install file.
 */

/**
 * Implements hook_schema().
 */
function discount_schema() {

  $schema['discount_discount'] = array(
    'fields' => array(
      'discount' => array(
        'type' => 'varchar',
        'length' => 10,
        'not null' => TRUE,
      ),
      'uid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('discount'),
  );

  return $schema;
}
