<?php

/**
 * @file
 * New status form module file.
 *
 * O module for site status messages in a popup window.
 */

/**
 * Implements hook_menu().
 */
function new_status_form_menu() {
  $items['admin/config/new_status_form'] = array(
    'title' => 'New status form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('new_status_form_config_form'),
    'access arguments' => array('administer site configuration'),
  );
 
  return $items;
}


/**
 * Form admin configuration.
 */
function new_status_form_config_form($form, &$form_state) {
  $form = array();
  
  $form['form_height'] = array(
    '#title' => t('Height window'),
    '#type' => 'radios',
    '#options' => array(160 => "160px", 200 => "200px", 400 => "400px"),
    '#default_value' => variable_get('form_height', 200),
  );

  $form['form_width'] = array(
    '#title' => t('Width window'),
    '#type' => 'radios',
    '#options' => array(200 => "200px", 500 => "500px", 800 => "800px"),
    '#default_value' => variable_get('form_width', 500),
  );

  $form['form_bg'] = array(
    '#title' => t('Color window'),
    '#type' => 'radios',
    '#options' => array('darkgoldenrod' => "darkgoldenrod", 'burlywood' => "burlywood", 'coral' => "coral"),
    '#default_value' => variable_get('form_bg', 'burlywood'),
  );
  return system_settings_form($form);
}

/**
 * Implements init().
 */
function new_status_form_init() {
  drupal_add_library('system', 'ui.draggable');
}

/**
 * Implements theme_registry_alter().
 */
function new_status_form_theme_registry_alter(&$theme_registry) {
  $theme_registry['status_messages']['function'] = 'new_status_form_get_message';
}

/**
 * Implements form_theme().
 */
function new_status_form_theme() {  
  return array(
    'new_status_form' => array(
      'variables' => array(
        'body' => NULL,
      ),
      'template' => 'theme/tpl/new_status_form_template',
    ),
  );
}

/**
 * Return title and messages.
 *
 * @return array
 *   $list
 */
function new_status_form_get_message() {
  drupal_add_js(array(
    'new_status' => array(
      'form_height' => variable_get('form_height'),
      'form_width' => variable_get('form_width'),
      'form_bg' => variable_get('form_bg'),
    ),
  ), 'setting');

  foreach (drupal_get_messages() as $type => $messages) {
    foreach ($messages as $message) {
      $list[$type][] = $message;
    }
  }

  if (isset($list)) {
    return theme('new_status_form', array('body' => $list));
  }
}
