<?php

/**
 * @file
 * New status form module file.
 *
 * Module for site status messages in a popup window.
 */

/**
 * Implements hook_menu().
 */
function new_status_form_menu() {
  $items['admin/config/new-status-form'] = array(
    'title' => 'New status form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('new_status_form_config_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/new_status_form.form.inc',
  );

  return $items;
}

/**
 * Implements theme_registry_alter().
 */
function new_status_form_theme_registry_alter(&$theme_registry) {
  $path = drupal_get_path('module', 'new_status_form');
  $theme_registry['status_messages']['includes'][] = $path . '/includes/new_status_form.common.inc';
  $theme_registry['status_messages']['function'] = 'new_status_form_get_message';
}

/**
 * Implements form_theme().
 */
function new_status_form_theme() {

  return array(
    'new_status_form' => array(
      'variables' => array(
        'body' => NULL,
      ),
      'template' => 'theme/tpl/new_status_form_template',
    ),
  );
}
