<?php

/**
 * @file
 * New status form module file.
 *
 * O module for site status messages in a popup window.
 */

/**
 * Start function.
 */
function new_status_form_theme_registry_alter(&$theme_registry) {
  $theme_registry['status_messages']['function'] = 'new_status_form_get_message';
}

/**
 * Include theme.
 */
function new_status_form_theme() {
  return array(
    'new_status_form' => array(
      'variables' => array(
        'body' => NULL,
      ),
      'template' => 'theme/tpl/new_status_form_template',
    ),
  );
}

/**
 * Return title and messages.
 */
function new_status_form_get_message() {
  foreach (drupal_get_messages() as $type => $messages) {
    foreach ($messages as $message) {
      $list[$type][] = $message;
    }
  }

  if (isset($list)) {
    return theme('new_status_form', array('body' => $list));
  }
}
