<?php

/**
 * @file
 * Login ajax module file.
 *
 * The module that modifies an existing entry form on the website so that it
 * works without a reboot.
 */

/**
 * Implements form_FORM_ID_alter().
 */
function login_ajax_form_user_login_block_alter(&$form, &$form_state, $form_id) {

  $form['actions']['submit']['#ajax'] = array(
    'callback' => 'login_ajax_form_user_login_callback',
    'wrapper' => 'user-login-form',
    'event' => 'click',
  );
}

/**
 * Implements form_FORM_ID_alter().
 */
function login_ajax_form_user_login_alter(&$form, &$form_state, $form_id) {

  $form['actions']['submit']['#ajax'] = array(
    'callback' => 'login_ajax_form_user_login_callback',
    'wrapper' => 'user-login',
    'event' => 'click',
  );
}

/**
 * Function returns form.
 *
 * @return array
 *   It returns a value depending on the state of user authentication.
 */
function login_ajax_form_user_login_callback(&$form, &$form_state, $form_id) {

  global $user;

  if ($user->uid) {
    $form = array();

    $form['label'] = array(
      '#markup' => variable_get('contact_form_information', t('Hello, !username! To see the website as a registered user go to this <a href="@user-url">link</a>.', array(
        '!username' => $user->name,
        '@user-url' => url('user'),
      ))),
    );
  }

  return $form;
}
