<?php

/**
 * @file
 * Login ajax module file.
 *
 * The module that modifies an existing entry form on the website so that it
 * works without a reboot.
 */

/**
 * Implements form_alter().
 */
function login_ajax_form_user_login_block_alter(&$form, &$form_state, $form_id) {

  $form['actions']['submit']['#ajax'] = array(
    'callback' => 'login_ajax_callback',
    'wrapper' => 'user-login-form',
    'event' => 'click',
  );
}

/**
 * Callback function.
 *
 * @return array
 *   It returns a value depending on the state of user authentication.
 */
function login_ajax_callback(&$form, &$form_state, $form_id) {

  global $user;

  $form = array();

  if ($user->uid) {
    $form['label'] = array(
      '#markup' => variable_get('contact_form_information', t('Hello, username! To see the website as a registered user go to this link.')),
    );
  }

  else {
    $form['label'] = array(
      '#markup' => variable_get('contact_form_information', t('Incorrect login and/or password!')),
    );
  }

  return $form;
}
