<?php

/**
 * @file
 * Internet reception module file.
 *
 * The user fills in a special form fields (Name, Email, Age, Subject, Message,
 * Captcha). All fields are required. Upon confirmation of the form data is
 * checked for correct input. Then a letter of reference data is sent to the
 * site administrator.
 */

/**
 * Implements hook_menu().
 */
function internet_reception_menu() {
  $items = array();

  $items['internet_reception'] = array(
    'title' => 'Internet reception',
    'description' => 'This is Internet reception',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('internet_reception_form'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
    'file' => 'includes/internet_reception.form.inc',
  );

  return $items;
}

/**
 * Implements hook_mail().
 */
function internet_reception_form_mail($key, &$message, $params) {
  $headers = array(
    'MIME-Version' => '1.0',
    'Content-Type' => 'text/html; charset=UTF-8;',
    'Content-Transfer-Encoding' => '8Bit',
    'X-Mailer' => 'Drupal',
  );

  foreach ($headers as $key => $value) {
    $message['headers'][$key] = $value;
  }

  $message['subject'] = $params['subject'];
  $message['body'] = $params['body'];
}
