<?php

/**
 * @file
 * Exchange Rates module file.
 *
 * It shows the Exchange Rates.
 */

require_once 'includes/exchange_rates.common.inc';

/**
 * Implements hook_menu().
 */
function exchange_rates_menu() {
  $items = array();

  $items['admin/config/exchange-rates'] = array(
    'title' => 'Node state',
    'page callback' => 'exchange_rates_page_forms',
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/exchange_rates.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_entity_info().
 */
function exchange_rates_entity_info() {
  $info['exchange_rates_entity'] = array(
    'label' => t('Entity exchange rates'),
    'entity class' => 'Entity',
    'metadata controller class' => 'ExchangeRatesEntityMetadataController',
    'controller class' => 'EntityAPIController',
    'module' => 'exchange_rates',
    'base table' => 'exchange_rates',
    'entity keys' => array(
      'id' => 'id',
    ),
  );

  return $info;
}

/**
 * Implements hook_views_api().
 */
function exchange_rates_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'exchange_rates'),
  );
}
